# Generated by Django 2.2 on 2023-08-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_onlineappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineappointment',
            name='link',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
